[package]
name = "rostware23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

args = "2.2.0"
getopts = "0.2.21"

rand = "0.8.5"

rostware23_lib = { path = "rostware23_lib" }
