[alias]
build-contest = "build --release --target=x86_64-unknown-linux-musl"

[profile.release]
overflow-checks = false
codegen-units = 1
opt-level = 3
lto = true

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "opt-level=3",
    "-C", "target-cpu=native"
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "opt-level=3",
    "-C", "target-cpu=broadwell"
]
